uploads = []

[[generated]]
id = "tkCbLYiYQM0YkTd3geyIp"
uri = "file://client/src/assets/optimized/sector-detailhandel.png"
type = "image"
title = "sector detailhandel"

[[generated]]
id = "8yq5iUaZemE7urGFRe0Jt"
uri = "file://client/src/assets/optimized/sector-horeca.png"
type = "image"
title = "sector horeca restaurant"

[[generated]]
id = "KT8Q-yRClch-LGHXZW1m_"
uri = "file://client/src/assets/optimized/sector-techniek.png"
type = "image"
title = "sector techniek"

[[generated]]
id = "M31_XC1mE8Dbu0I6ycH5S"
uri = "file://client/src/assets/optimized/sector-agrarisch.png"
type = "image"
title = "sector agrarisch"

[[outputs]]
id = "QrA78FbOfalijyMAB1Sx4"
uri = "file://.local/exports/openregio-source.zip"
type = "unspecified"
title = "OpenRegio broncode (zonder node_modules e.d.)"

[[outputs]]
id = "FM10311gmq2NDX_KwtLk5"
uri = "file://attached_assets/downloads/openregio-source.zip"
type = "unspecified"
title = "OpenRegio broncode (36 MB, zonder node_modules)"
